### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tintnc** [phanletrunghieu/dkhp-uit#1]
go build -o dkhp-uit main.go
main.go:11:2: cannot find package "github.com/phanletrunghieu/dkhp-uit/util" in any of:
	/usr/lib/go-1.11/src/github.com/phanletrunghieu/dkhp-uit/util (from $GOROOT)
	/root/go/src/github.com/phanletrunghieu/dkhp-uit/util (from $GOPATH)
make: *** [makefile:3: build] Error 1

Chạy make build hiện lỗi này là thế nào nhỉ anh?

**Comment by lpnam0201** [comment]
Bạn thử sửa tạm 
"github.com/phanletrunghieu/dkhp-uit/util" 
thành 
"./util"

**Comment by tintnc** [comment]
Fix được rồi nhé, cảm ơn anh nhiều :3
